### ISSUE TITLE
clash全局模式

### ISSUE THREAD

**Issue by dollar-cat** [LondonX/clash_flt#7]
你的答案是 目前的方法是重载配置文件中的rules，设置为MATCH,Proxy即全局模式。
可以尝试使用[yaml_edit](https://pub.dev/packages/yaml_edit)来实现yaml的编辑。

我尝试了 闪退 我查看了一下关于MATCH的介绍 规则最后一行是MATCH,Final，表示如果客户端运行在基于规则模式，如果匹配到上面的规则，就按照规则定义的路由走，否则走Final这个规则组 我没有proxy这个规则组 我需要去手写一个嘛
<img width="1428" alt="截屏2023-07-22 08 23 11" src="https://github.com/LondonX/clash_flt/assets/72382917/a111dd00-c5a4-4f27-a39e-2fd0d365bc04">

**Comment by LondonX** [comment]
要看你的clash配置文件里`proxy-groups`配置了哪些代理组。
```yaml
proxy-groups:
- name: Auto
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - Node 1
  - Node 2
  - Node 3
  - Node 4
- name: Proxy
  type: select
  proxies:
  - Node 1
  - Node 2
  - Node 3
  - Node 4
```
例如在这段配置中的`Auto`和`Proxy`
